!function(e){function r(e,r,o){return 4===arguments.length?t.apply(this,arguments):void n(e,{declarative:!0,deps:r,declare:o})}function t(e,r,t,o){n(e,{declarative:!1,deps:r,executingRequire:t,execute:o})}function n(e,r){r.name=e,e in v||(v[e]=r),r.normalizedDeps=r.deps}function o(e,r){if(r[e.groupIndex]=r[e.groupIndex]||[],-1==g.call(r[e.groupIndex],e)){r[e.groupIndex].push(e);for(var t=0,n=e.normalizedDeps.length;n>t;t++){var a=e.normalizedDeps[t],u=v[a];if(u&&!u.evaluated){var d=e.groupIndex+(u.declarative!=e.declarative);if(void 0===u.groupIndex||u.groupIndex<d){if(void 0!==u.groupIndex&&(r[u.groupIndex].splice(g.call(r[u.groupIndex],u),1),0==r[u.groupIndex].length))throw new TypeError("Mixed dependency cycle detected");u.groupIndex=d}o(u,r)}}}}function a(e){var r=v[e];r.groupIndex=0;var t=[];o(r,t);for(var n=!!r.declarative==t.length%2,a=t.length-1;a>=0;a--){for(var u=t[a],i=0;i<u.length;i++){var s=u[i];n?d(s):l(s)}n=!n}}function u(e){return y[e]||(y[e]={name:e,dependencies:[],exports:{},importers:[]})}function d(r){if(!r.module){var t=r.module=u(r.name),n=r.module.exports,o=r.declare.call(e,function(e,r){if(t.locked=!0,"object"==typeof e)for(var o in e)n[o]=e[o];else n[e]=r;for(var a=0,u=t.importers.length;u>a;a++){var d=t.importers[a];if(!d.locked)for(var i=0;i<d.dependencies.length;++i)d.dependencies[i]===t&&d.setters[i](n)}return t.locked=!1,r},{id:r.name});t.setters=o.setters,t.execute=o.execute;for(var a=0,i=r.normalizedDeps.length;i>a;a++){var l,s=r.normalizedDeps[a],c=v[s],f=y[s];f?l=f.exports:c&&!c.declarative?l=c.esModule:c?(d(c),f=c.module,l=f.exports):l=p(s),f&&f.importers?(f.importers.push(t),t.dependencies.push(f)):t.dependencies.push(null),t.setters[a]&&t.setters[a](l)}}}function i(e){var r,t=v[e];if(t)t.declarative?f(e,[]):t.evaluated||l(t),r=t.module.exports;else if(r=p(e),!r)throw new Error("Unable to load dependency "+e+".");return(!t||t.declarative)&&r&&r.__useDefault?r["default"]:r}function l(r){if(!r.module){var t={},n=r.module={exports:t,id:r.name};if(!r.executingRequire)for(var o=0,a=r.normalizedDeps.length;a>o;o++){var u=r.normalizedDeps[o],d=v[u];d&&l(d)}r.evaluated=!0;var c=r.execute.call(e,function(e){for(var t=0,n=r.deps.length;n>t;t++)if(r.deps[t]==e)return i(r.normalizedDeps[t]);throw new TypeError("Module "+e+" not declared as a dependency.")},t,n);void 0!==c&&(n.exports=c),t=n.exports,t&&t.__esModule?r.esModule=t:r.esModule=s(t)}}function s(r){var t={};if(("object"==typeof r||"function"==typeof r)&&r!==e)if(m)for(var n in r)"default"!==n&&c(t,r,n);else{var o=r&&r.hasOwnProperty;for(var n in r)"default"===n||o&&!r.hasOwnProperty(n)||(t[n]=r[n])}return t["default"]=r,x(t,"__useDefault",{value:!0}),t}function c(e,r,t){try{var n;(n=Object.getOwnPropertyDescriptor(r,t))&&x(e,t,n)}catch(o){return e[t]=r[t],!1}}function f(r,t){var n=v[r];if(n&&!n.evaluated&&n.declarative){t.push(r);for(var o=0,a=n.normalizedDeps.length;a>o;o++){var u=n.normalizedDeps[o];-1==g.call(t,u)&&(v[u]?f(u,t):p(u))}n.evaluated||(n.evaluated=!0,n.module.execute.call(e))}}function p(e){if(I[e])return I[e];if("@node/"==e.substr(0,6))return I[e]=s(D(e.substr(6)));var r=v[e];if(!r)throw"Module "+e+" not present.";return a(e),f(e,[]),v[e]=void 0,r.declarative&&x(r.module.exports,"__esModule",{value:!0}),I[e]=r.declarative?r.module.exports:r.esModule}var v={},g=Array.prototype.indexOf||function(e){for(var r=0,t=this.length;t>r;r++)if(this[r]===e)return r;return-1},m=!0;try{Object.getOwnPropertyDescriptor({a:0},"a")}catch(h){m=!1}var x;!function(){try{Object.defineProperty({},"a",{})&&(x=Object.defineProperty)}catch(e){x=function(e,r,t){try{e[r]=t.value||t.get.call(e)}catch(n){}}}}();var y={},D="undefined"!=typeof System&&System._nodeRequire||"undefined"!=typeof require&&"undefined"!=typeof require.resolve&&"undefined"!=typeof process&&process.platform&&require,I={"@empty":{}};return function(e,n,o,a){return function(u){u(function(u){for(var d={_nodeRequire:D,register:r,registerDynamic:t,get:p,set:function(e,r){I[e]=r},newModule:function(e){return e}},i=0;i<n.length;i++)(function(e,r){r&&r.__esModule?I[e]=r:I[e]=s(r)})(n[i],arguments[i]);a(d);var l=p(e[0]);if(e.length>1)for(var i=1;i<e.length;i++)p(e[i]);return o?l["default"]:l})}}}("undefined"!=typeof self?self:global)

(["artifacts/transpiled-renovation/localization/cldr-data/first_day_of_week_data.js"], [], true, function($__System) {
var require = this.require, exports = this.exports, module = this.module;
$__System.registerDynamic("artifacts/transpiled-renovation/localization/cldr-data/first_day_of_week_data.js", [], true, function ($__require, exports, module) {
  "use strict";

  var global = this || self,
      GLOBAL = global;
  exports.default = void 0;
  /* eslint-disable node/no-unsupported-features/es-syntax */
  // !!! AUTO-GENERATED FILE, DO NOT EDIT
  var _default = {
    "af-NA": 1,
    "agq": 1,
    "ak": 1,
    "ar": 6,
    "ar-EH": 1,
    "ar-ER": 1,
    "ar-KM": 1,
    "ar-LB": 1,
    "ar-MA": 1,
    "ar-MR": 1,
    "ar-PS": 1,
    "ar-SO": 1,
    "ar-SS": 1,
    "ar-TD": 1,
    "ar-TN": 1,
    "asa": 1,
    "ast": 1,
    "az": 1,
    "az-Cyrl": 1,
    "bas": 1,
    "be": 1,
    "bem": 1,
    "bez": 1,
    "bg": 1,
    "bm": 1,
    "br": 1,
    "bs": 1,
    "bs-Cyrl": 1,
    "ca": 1,
    "ce": 1,
    "cgg": 1,
    "ckb": 6,
    "cs": 1,
    "cy": 1,
    "da": 1,
    "de": 1,
    "dje": 1,
    "dsb": 1,
    "dua": 1,
    "dyo": 1,
    "ee": 1,
    "el": 1,
    "en-001": 1,
    "en-AE": 6,
    "en-BI": 1,
    "en-MP": 1,
    "en-MV": 5,
    "en-SD": 6,
    "eo": 1,
    "es": 1,
    "et": 1,
    "eu": 1,
    "ewo": 1,
    "fa": 6,
    "ff": 1,
    "ff-Adlm": 1,
    "fi": 1,
    "fo": 1,
    "fr": 1,
    "fr-DJ": 6,
    "fr-DZ": 6,
    "fr-SY": 6,
    "fur": 1,
    "fy": 1,
    "ga": 1,
    "gd": 1,
    "gl": 1,
    "gsw": 1,
    "gv": 1,
    "ha": 1,
    "hr": 1,
    "hsb": 1,
    "hu": 1,
    "hy": 1,
    "ia": 1,
    "ig": 1,
    "is": 1,
    "it": 1,
    "jgo": 1,
    "jmc": 1,
    "ka": 1,
    "kab": 6,
    "kde": 1,
    "kea": 1,
    "khq": 1,
    "kk": 1,
    "kkj": 1,
    "kl": 1,
    "ko-KP": 1,
    "ksb": 1,
    "ksf": 1,
    "ksh": 1,
    "ku": 1,
    "kw": 1,
    "ky": 1,
    "lag": 1,
    "lb": 1,
    "lg": 1,
    "ln": 1,
    "lrc": 6,
    "lt": 1,
    "lu": 1,
    "lv": 1,
    "mas-TZ": 1,
    "mfe": 1,
    "mg": 1,
    "mgo": 1,
    "mi": 1,
    "mk": 1,
    "mn": 1,
    "ms": 1,
    "mua": 1,
    "mzn": 6,
    "naq": 1,
    "nds": 1,
    "nl": 1,
    "nmg": 1,
    "nnh": 1,
    "no": 1,
    "nus": 1,
    "nyn": 1,
    "os": 1,
    "pcm": 1,
    "pl": 1,
    "ps": 6,
    "pt-AO": 1,
    "pt-CH": 1,
    "pt-CV": 1,
    "pt-GQ": 1,
    "pt-GW": 1,
    "pt-LU": 1,
    "pt-ST": 1,
    "pt-TL": 1,
    "qu-BO": 1,
    "qu-EC": 1,
    "rm": 1,
    "rn": 1,
    "ro": 1,
    "rof": 1,
    "ru": 1,
    "rw": 1,
    "rwk": 1,
    "sah": 1,
    "sbp": 1,
    "sc": 1,
    "se": 1,
    "ses": 1,
    "sg": 1,
    "shi": 1,
    "shi-Latn": 1,
    "si": 1,
    "sk": 1,
    "sl": 1,
    "smn": 1,
    "so": 1,
    "so-DJ": 6,
    "sq": 1,
    "sr": 1,
    "sr-Latn": 1,
    "sv": 1,
    "sw": 1,
    "ta-LK": 1,
    "ta-MY": 1,
    "teo": 1,
    "tg": 1,
    "ti-ER": 1,
    "tk": 1,
    "to": 1,
    "tr": 1,
    "tt": 1,
    "twq": 1,
    "tzm": 1,
    "uk": 1,
    "uz": 1,
    "uz-Arab": 6,
    "uz-Cyrl": 1,
    "vai": 1,
    "vai-Latn": 1,
    "vi": 1,
    "vun": 1,
    "wae": 1,
    "wo": 1,
    "xog": 1,
    "yav": 1,
    "yi": 1,
    "yo": 1,
    "zgh": 1
  };
  exports.default = _default;
  module.exports = exports.default;
  module.exports.default = exports.default;
});
})
(function(factory) {
  if (typeof define == 'function' && define.amd)
    define([], factory);
  else if (typeof module == 'object' && module.exports && typeof require == 'function')
    module.exports = factory();
  else
    factory();
});
//# sourceMappingURL=first_day_of_week_data.js.map