"use strict";

exports.VERTICAL_GROUP_ORIENTATION = exports.HORIZONTAL_GROUP_ORIENTATION = void 0;
const VERTICAL_GROUP_ORIENTATION = 'vertical';
exports.VERTICAL_GROUP_ORIENTATION = VERTICAL_GROUP_ORIENTATION;
const HORIZONTAL_GROUP_ORIENTATION = 'horizontal';
exports.HORIZONTAL_GROUP_ORIENTATION = HORIZONTAL_GROUP_ORIENTATION;