"use strict";

exports.COLOR_MODE_TARGET = exports.COLOR_MODE_SOURCE = exports.COLOR_MODE_NONE = exports.COLOR_MODE_GRADIENT = void 0;
const COLOR_MODE_GRADIENT = 'gradient';
exports.COLOR_MODE_GRADIENT = COLOR_MODE_GRADIENT;
const COLOR_MODE_SOURCE = 'source';
exports.COLOR_MODE_SOURCE = COLOR_MODE_SOURCE;
const COLOR_MODE_TARGET = 'target';
exports.COLOR_MODE_TARGET = COLOR_MODE_TARGET;
const COLOR_MODE_NONE = 'none';
exports.COLOR_MODE_NONE = COLOR_MODE_NONE;